# Generated by Django 6.0.5 on 2026-05-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
